# docker-compose.yml

services:
  greet:
    image: greet_img
    build: 
      # determine the working directory on the host
      context: .
      dockerfile: docker/Dockerfile
    container_name: greet
    environment:
      - PASSWORD=${PASSWORD}
    volumes:
      - ./app:/home/app
      - ./img:/home/img
    # specifies the default working directory in the container at the time of service execution
    # ie independently of the WORKDIR directive defined in the Dockerfile
    working_dir: /home/app
    command: python main.py

  greet_test:
      image: greet_img_test
      build: 
        context: .
        dockerfile: docker/Dockerfile
        args:
          REQUIREMENTS_4TESTS: requirements_4tests.txt
      container_name: greet_test
      environment:
        - PASSWORD=${PASSWORD}
      volumes:
        - ./app:/home/app
        - ./img:/home/img
        - ./test_reports:/home/test_reports
      working_dir: /home
      command: pytest --junitxml=/home/test_reports/pytest_report.xml --html=/home/test_reports/pytest_report.html
